webgl.siteprompt2=Soll %S einen WebGL-Kontext erstellen dürfen?
webgl.siteprompt2.warning=Dies kann dazu dienen, Ihren Computer eindeutig zu identifizieren.
webgl.block=Blockieren
webgl.block.accesskey=B
webgl.allow2=Erlauben
webgl.allow2.accesskey=E
webgl.remember2=Diese Entscheidung merken
eme.siteprompt2=%S die Wiedergabe von DRM-kontrollierten Inhalten erlauben?
eme.block=Blockieren
eme.block.accesskey=B
eme.allow2=Erlauben
eme.allow2.accesskey=E
eme.remember2=Diese Entscheidung merken
