webgl.siteprompt2=Soll %S einen WebGL-Kontext erstellen dürfen?
webgl.siteprompt2.warning=Dies kann dazu dienen, Ihren Computer eindeutig zu identifizieren.
webgl.block=Blockieren
webgl.block.accesskey=B
webgl.allow2=Erlauben
webgl.allow2.accesskey=E
webgl.remember2=Diese Entscheidung merken
