webgl.siteprompt2=Soll %S erlaubt werden einen WebGL Kontext zu erstellen?
webgl.siteprompt2.warning=Dies könnte dazu genutzt werden deinen Rechner eindeutig zu identifizieren.
webgl.block=Blockieren
webgl.block.accesskey=B
webgl.allow2=Erlauben
webgl.allow2.accesskey=E
webgl.remember2=Diese Entscheidung merken
