webgl.siteprompt2=Tillåt %S att skapa ett WebGL kontext?
webgl.siteprompt2.warning=Detta kan användas för att unikt identifiera din dator.
webgl.block=Blockera
webgl.block.accesskey=B
webgl.allow2=Tillåt
webgl.allow2.accesskey=A
webgl.remember2=Kom ihåg detta beslut
