webgl.siteprompt2=Povolit stránce %S vytvořit kontext WebGL?
webgl.siteprompt2.warning=Tato funkce může být použita k unikátní identifikaci vašeho počítače.
webgl.block=Zablokovat
webgl.block.accesskey=B
webgl.allow2=Povolit
webgl.allow2.accesskey=P
webgl.remember2=Zapamatovat si tuto volbu
