webgl.siteprompt2=Zezwolić %S na utworzenie kontekstu WebGL?
webgl.siteprompt2.warning=To może być wykorzystane do unikalnej identyfikacji Twojego komputera.
webgl.block=Blokuj
webgl.block.accesskey=B
webgl.allow2=Zezwól
webgl.allow2.accesskey=Z
webgl.remember2=Zapamiętaj tę decyzję
