webgl.siteprompt2=Zezwolić %S na utworzenie kontekstu WebGL?
webgl.siteprompt2.warning=To może być wykorzystane do unikalnej identyfikacji Twojego komputera.
webgl.block=Blokuj
webgl.block.accesskey=B
webgl.allow2=Zezwól
webgl.allow2.accesskey=Z
webgl.remember2=Zapamiętaj tę decyzję
eme.siteprompt2=Czy zezwolić witrynie „%S” na odtwarzanie treści chronionych przez DRM?
eme.block=Blokuj
eme.block.accesskey=B
eme.allow2=Zezwól
eme.allow2.accesskey=Z
eme.remember2=Zapamiętaj tę decyzję
