name: Push
on: [push]

jobs:
  push:
    runs-on: delta
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: make fetch-upstream-woodpecker
      - run: make check-patchfail-woodpecker
