name: Test

on:
  push:
  workflow_dispatch:
    inputs:
      Target:
        description: 'Target Platform'
        required: true
        default: 'linux'
        type: choice
        options:
          - all
          - linux
          - windows
          - macos
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  test-linux:
    if: inputs.Target == 'all' || inputs.Target == 'linux' || inputs.Target == ''
    runs-on: docker
    container:
      image: codeberg.org/librewolf/bsys6:dind
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          apt-get update && apt-get -y upgrade
          apt-get -y install build-essential curl jq make python3 python3-dev python3-pip wget unzip git pigz gnupg

      - name: Fetching Firefox Source
        run: |
          make fetch

      - name: Check Patchfail
        run: |
          sh -c "./scripts/check-patchfail.sh"
      
      - name: Test Build
        run: |
          make test-linux

      - name: Upload artifacts
        uses: https://data.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: linux-test
          path: |
            librewolf-*.tar.xz
            mozconfig.txt
          retention-days: ${{ github.event_name == 'push' && 3 || 14 }}

  test-windows:
    if: inputs.Target == 'all' || inputs.Target == 'windows'
    runs-on: docker
    container:
      image: codeberg.org/librewolf/bsys6:dind
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          apt-get update && apt-get -y upgrade
          apt-get -y install build-essential curl jq make python3 python3-dev python3-pip wget unzip git pigz gnupg

      - name: Fetching Firefox Source
        run: |
          make fetch

      - name: Check Patchfail
        run: |
          sh -c "./scripts/check-patchfail.sh"
      
      - name: Test Build
        run: |
          make test-windows

      - name: Upload artifacts
        uses: https://data.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: windows-test
          path: |
            librewolf-*.zip
            mozconfig.txt
          retention-days: ${{ github.event_name == 'push' && 3 || 14 }}

  test-macos:
    if: inputs.Target == 'all' || inputs.Target == 'macos'
    runs-on: docker
    container:
      image: codeberg.org/librewolf/bsys6:dind
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          apt-get update && apt-get -y upgrade
          apt-get -y install build-essential curl jq make python3 python3-dev python3-pip wget unzip git pigz gnupg

      - name: Fetching Firefox Source
        run: |
          make fetch

      - name: Check Patchfail
        run: |
          sh -c "./scripts/check-patchfail.sh"
      
      - name: Test Build
        run: |
          make test-macos

      - name: Upload artifacts
        uses: https://data.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: macos-test
          path: |
            librewolf-*.tar.gz
            mozconfig.txt
          retention-days: ${{ github.event_name == 'push' && 3 || 14 }}
