webgl.siteprompt2=%s에 WebGL 컨텍스트 생성을 허용하시겠습니까?
webgl.siteprompt2.warning=당신의 컴퓨터를 고유하게 식별하는 데에 사용될 수 있습니다.
webgl.block=차단
webgl.block.accesskey=B
webgl.allow2=허용
webgl.allow2.accesskey=A
webgl.remember2=이 결정을 기억
eme.siteprompt2=%S에서 DRM 제어 콘텐츠를 재생하도록 허용하시겠습니까?
eme.block=차단
eme.block.accesskey=B
eme.allow2=허용
eme.allow2.accesskey=A
eme.remember2=이 결정을 기억
