webgl.allow2.accesskey=А
webgl.siteprompt2=Дозволити %S створити контекст WebGL ?
webgl.siteprompt2.warning=Це може бути використано, щоб ідентифікувати ваш комп'ютер.
webgl.remember2=Запам'ятати це рішення
webgl.block.accesskey=Б
webgl.allow2=Дозволити
webgl.block=Блокувати
eme.siteprompt2=Дозволити %S відтворювати вміст, контрольований DRM?
eme.block=Блокувати
eme.block.accesskey=Б
eme.allow2=Дозволити
eme.allow2.accesskey=А
eme.remember2=Запам'ятати цей вибір
