webgl.siteprompt2=Wilt u %S toestaan om een WebGL-context aan te maken?
webgl.siteprompt2.warning=Dit kan worden gebruikt om uw computer te identificeren.
webgl.block=Blokkeren
webgl.block.accesskey=B
webgl.allow2=Toestaan
webgl.allow2.accesskey=T
webgl.remember2=Keuze onthouden
eme.siteprompt2=%S toestaan om DRM-gecontroleerde inhoud af te spelen?
eme.block=Blokkeren
eme.block.accesskey=B
eme.allow2=Toestaan
eme.allow2.accesskey=T
eme.remember2=Keuze onthouden
