webgl.siteprompt2=Wil je %S toestaan om een WebGL-context aan te maken?
webgl.siteprompt2.warning=Dit kan worden gebruikt om je computer te identificeren.
webgl.block=Blokkeren
webgl.block.accesskey=B
webgl.allow2=Toestaan
webgl.allow2.accesskey=T
webgl.remember2=Keuze onthouden
