webgl.siteprompt2=Permitir a %S crear un contexto WebGL?
webgl.siteprompt2.warning=Podería utilizarse para identificar de xeito único a túa computadora.
webgl.block=Bloquear
webgl.block.accesskey=B
webgl.allow2=Autorizar
webgl.allow2.accesskey=A
webgl.remember2=Lembrar esta decisión
