eme.siteprompt2=Permite ca %S să redea conținut controlat de DRM?
eme.block=Blochează
eme.block.accesskey=B
eme.allow2=Permite
eme.allow2.accesskey=P
eme.remember2=Ține minte această decizie
webgl.siteprompt2=Permite ca %S să creeze un context WebGL?
webgl.siteprompt2.warning=Lucrul acesta ar putea fi folosit pentru ați identifica în mod unic calculatorul.
webgl.block=Blochează
webgl.block.accesskey=B
webgl.allow2=Permite
webgl.allow2.accesskey=P
webgl.remember2=Ține minte această decizie
