webgl.siteprompt2=Gasa %S gul testen WebGL?
webgl.siteprompt2.warning=Martesen hemm a wra bos devnydhys rag aswon dha amontyell.
webgl.block=Lettya
webgl.block.accesskey=L
webgl.allow2=Gasa
webgl.allow2.accesskey=G
webgl.remember2=Kofhe an ervirans ma
