webgl.siteprompt2=Të lejohet %S të krijojë kontekst WebGL?
webgl.siteprompt2.warning=Kjo mund të përdoret për të identifikuar në mënyrë unike kompjuterin tuaj.
webgl.block=Bllokoje
webgl.block.accesskey=B
webgl.allow2=Lejoje
webgl.allow2.accesskey=L
webgl.remember2=Mbaje mend këtë vendim
