webgl.allow2.accesskey=C
webgl.siteprompt2=Ceadaigh %S comhthéacs WebGL a chruthú?
webgl.siteprompt2.warning=Féadfar é seo a úsáid chun do ríomhaire a aithint go huathúil.
webgl.remember2=Cuimhnigh ar an gcinneadh seo
webgl.block.accesskey=B
webgl.allow2=Ceadaigh
webgl.block=Bloc
