webgl.siteprompt2=Autoriser %S à créer un contexte WebGL ?
webgl.siteprompt2.warning=Ceci pourrait être utilisé pour identifier de manière unique votre ordinateur.
webgl.block=Bloquer
webgl.allow2=Autoriser
webgl.remember2=Se souvenir de cette décision
webgl.block.accesskey=B
webgl.allow2.accesskey=A
eme.siteprompt2=Autoriser %S à lire du contenu contrôlé par DRM ?
eme.block=Bloquer
eme.block.accesskey=B
eme.allow2=Autoriser
eme.allow2.accesskey=A
eme.remember2=Se souvenir de cette décision
