webgl.siteprompt2=Autoriser %S à créer un contexte WebGL ?
webgl.siteprompt2.warning=Ceci pourrait être utilisé pour identifier de manière unique votre ordinateur.
webgl.block=Bloquer
webgl.allow2=Autoriser
webgl.remember2=Se souvenir de cette décision
