webgl.siteprompt2=Izinkan %S membuat konteks WebGL?
webgl.siteprompt2.warning=Ini dapat digunakan untuk mengidentifikasi komputer Anda secara unik.
webgl.block=Blokir
webgl.block.accesskey=B
webgl.allow2=Izinkan
webgl.allow2.accesskey=A
webgl.remember2=Ingat keputusan ini
eme.siteprompt2=
eme.block=Blokir
eme.block.accesskey=B
eme.allow2=Izinkan
eme.allow2.accesskey=A
eme.remember2=Ingat keputusan ini
