webgl.siteprompt2=%S sayfasına WebGL İçeriği oluşturmasına izin ver?
webgl.siteprompt2.warning=Bu spesifik olarak senin bilgisayarının tespit edilmesinde kullanılabilir.
webgl.block=Engelle
webgl.block.accesskey=E
webgl.allow2=İzin ver
webgl.allow2.accesskey=İ
webgl.remember2=Bu tercihi hatırla
eme.siteprompt2=%S sitesi DRM denetimli içerikleri oynatabilsin mi?
eme.block=Engelle
eme.block.accesskey=E
eme.allow2=İzin ver
eme.allow2.accesskey=İ
eme.remember2=Bu tercihi hatırla
