webgl.siteprompt2=%S sayfasına WebGL İçeriği oluşturmasına izin ver?
webgl.siteprompt2.warning=Bu spesifik olarak senin bilgisayarının tespit edilmesinde kullanılabilir.
webgl.block=Engelle
webgl.block.accesskey=E
webgl.allow2=İzin ver
webgl.allow2.accesskey=İ
webgl.remember2=Bu tercihi hatırla
