eme.siteprompt2=Ĉu permesi al %S ludi DRM-kontrolitan enhavon?
eme.block=Bloki
eme.block.accesskey=B
eme.allow2=Permesi
eme.allow2.accesskey=P
eme.remember2=Memori tiun ĉi decidon
webgl.siteprompt2=Ĉu permesi al %S krei kuntekston de WebGL?
webgl.siteprompt2.warning=Ĉi tio povas esti uzata por unika identigo de via komputilo.
webgl.block=Bloki
webgl.block.accesskey=B
webgl.allow2=Permesi
webgl.allow2.accesskey=P
webgl.remember2=Memori tiun ĉi decidon
