webgl.siteprompt2=Engedélyezi a(z) %S számára, hogy WebGL-környezetet hozzon létre?
webgl.siteprompt2.warning=Ez a számítógép egyedi azonosítására használható.
webgl.block=Tiltás
webgl.block.accesskey=B
webgl.allow2=Engedélyezés
webgl.allow2.accesskey=A
webgl.remember2=Jegyezze meg ezt a döntést
eme.siteprompt2=Engedélyezi, hogy a(z) %S DRM által vezérelt tartalmat játsszon le?
eme.block=Tiltás
eme.block.accesskey=B
eme.allow2=Engedélyezés
eme.allow2.accesskey=A
eme.remember2=Jegyezze meg ezt a döntést
