webgl.siteprompt2=Engedélyezi a(z) %S számára, hogy WebGL-környezetet hozzon létre?
webgl.siteprompt2.warning=Ez a számítógép egyedi azonosítására használható.
webgl.block=Tiltás
webgl.block.accesskey=B
webgl.allow2=Engedélyezés
webgl.allow2.accesskey=A
webgl.remember2=Jegyezze meg ezt a döntést
