webgl.siteprompt2=Saako %S luoda WebGL-kontekstin?
webgl.siteprompt2.warning=Tätä voidaan hyödyntää tietokoneen yksilöintiin.
webgl.block=Estä
webgl.block.accesskey=E
webgl.allow2=Salli
webgl.allow2.accesskey=S
webgl.remember2=Muista tämä valinta
