webgl.siteprompt2=Saako %S luoda WebGL-kontekstin?
webgl.siteprompt2.warning=Tätä voidaan hyödyntää tietokoneen yksilöintiin.
webgl.block=Estä
webgl.block.accesskey=E
webgl.allow2=Salli
webgl.allow2.accesskey=S
webgl.remember2=Muista tämä valinta
eme.siteprompt2=Sallitko, että %S toistaa DRM-suojattua sisältöä?
eme.block=Estä
eme.block.accesskey=E
eme.allow2=Salli
eme.allow2.accesskey=S
eme.remember2=Muista tämä valinta
