FROM debian:trixie-slim as base

# Add packages
RUN apt update -y && apt upgrade -y
RUN apt install -y \
  xwayland-run \
  dbus \
  mold \
  build-essential \
  python3 \
  python3-dev \
  python3-pip \
  wget \
  unzip \
  git \
  sudo \
  gpg \
  firefox-esr

# Add builder user with sudo privilege
RUN useradd -m builder
RUN echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/builder

CMD su builder -c /usr/bin/env bash

FROM base as builder
COPY build-hyperfox.sh /home/builder/
RUN chmod +x /home/builder/build-hyperfox.sh
ENTRYPOINT ["/home/builder/build-hyperfox.sh"]

FROM base as package-deb
COPY build-deb.sh /home/builder/
COPY linux.hyperfox.desktop.in /home/builder/
RUN chmod +x /home/builder/build-deb.sh
ENTRYPOINT ["/home/builder/build-deb.sh"]

FROM archlinux:base-devel as package-arch

# Add packages
RUN pacman -Syu --noconfirm \
  git \
  gtk3 \
  libxt \
  startup-notification \
  mime-types \
  dbus \
  nss \
  ttf-font \
  libpulse \
  ffmpeg \
  zlib

# Add builder user with sudo privilege
RUN useradd -m builder
RUN echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/builder

COPY build-pkg.sh /home/builder
RUN chmod +x /home/builder/build-pkg.sh
CMD su builder -c /usr/bin/env bash
ENTRYPOINT ["/home/builder/build-pkg.sh"]
