webgl.allow2.accesskey=A
webgl.siteprompt2=Permitir %S criar um contexto WebGL?
webgl.siteprompt2.warning=Isso pode ser usado para identificar seu computador de maneira individual.
webgl.remember2=Lembrar desta decisão
webgl.block.accesskey=B
webgl.allow2=Permitir
webgl.block=Bloquear
eme.siteprompt2=Permitir que %S reproduza conteúdo controlado por direitos autorais?
eme.block=Bloquear
eme.block.accesskey=B
eme.allow2=Permitir
eme.allow2.accesskey=A
eme.remember2=Lembrar desta decisão
