webgl.allow2.accesskey=A
webgl.siteprompt2=Permitir %S criar um contexto WebGL?
webgl.siteprompt2.warning=Isso pode ser usado para identificar seu computador de maneira individual.
webgl.remember2=Lembrar desta decisão
webgl.block.accesskey=B
webgl.allow2=Permitir
webgl.block=Bloquear
