webgl.allow2.accesskey=
webgl.siteprompt2=%S কে একটি WebGL কাজের পরিবেশ তৈরি করার অনুমতি দিবেন?
webgl.siteprompt2.warning=
webgl.remember2=
webgl.block.accesskey=
webgl.allow2=
webgl.block=
eme.siteprompt2=%Sকে ডিআরএম-নিয়ন্ত্রিত মিডিয়া প্লে করতে দিবে?
eme.block=
eme.block.accesskey=
eme.allow2=
eme.allow2.accesskey=
eme.remember2=
