webgl.siteprompt2=Kas lubad, et %S loob WebGL-i konteksti?
webgl.siteprompt2.warning=Seda on võimalik kasutada sinu arvuti unikaalseks tuvastamiseks.
webgl.block=Blokeeri
webgl.block.accesskey=B
webgl.allow2=Luba
webgl.allow2.accesskey=A
webgl.remember2=Jäta see otsus meelde
