webgl.allow2.accesskey=A
webgl.siteprompt2=Consenti a %S di creare un contesto WebGL?
webgl.siteprompt2.warning=Questo potrebbe essere usato per identificare univocamente il tuo computer.
webgl.remember2=Ricorda questa scelta
webgl.block.accesskey=B
webgl.allow2=Consenti
webgl.block=Blocca
eme.siteprompt2=Consentire a %S di riprodurre contenuti protetti da DRM?
eme.block=Blocca
eme.block.accesskey=B
eme.allow2=Consenti
eme.allow2.accesskey=A
eme.remember2=Ricorda questa scelta
