webgl.block=Asteng bike
webgl.block.accesskey=B
webgl.allow2=Bihêle
webgl.allow2.accesskey=A
webgl.remember2=Vê biryarê bi bîr bîne
webgl.siteprompt2=Mafê bide %S da ku çarçoveya WebGL biafrîne?
webgl.siteprompt2.warning=Dibe ku ev ji bo naskirina taybet a kombersa te were bikaranîn.
eme.siteprompt2=Mafê bide %S ku naveroka hatiye kontrolkirin bi riya DRM bilîze?
eme.block=Asteng bike
eme.block.accesskey=B
eme.allow2=Bihêle
eme.allow2.accesskey=A
eme.remember2=Vê biryarê bi bîr bîne
