webgl.siteprompt2=¿Permitir que %S cree un contexto WebGL?
webgl.siteprompt2.warning=Esto puede utilizarse para identificar de forma única tu ordenador.
webgl.block=Bloquear
webgl.block.accesskey=B
webgl.allow2=Permitir
webgl.allow2.accesskey=A
webgl.remember2=Recuerda esta decisión
