webgl.allow2.accesskey=A
webgl.siteprompt2=Разрешить %S создать WebGL среду?
webgl.siteprompt2.warning=Это может использоваться для уникальной идентификации вашего компьютера.
webgl.remember2=Запомнить этот выбор
webgl.block.accesskey=B
webgl.allow2=Разрешить
webgl.block=Блокировка
eme.siteprompt2=Разрешить %S воспроизводить защищённое авторским правом содержимое?
eme.block=Блокировка
eme.block.accesskey=B
eme.allow2=Разрешить
eme.allow2.accesskey=A
eme.remember2=Запомнить этот выбор
